spring.application.name=StudentManagement
spring.application.name=student-management
# Cấu hình file Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=postgres
spring.datasource.password=170623
spring.datasource.driver-class-name=org.postgresql.Driver
# Cấu hình JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true